# Practical - Functional analysis of a gene list and sequence comparison

## Functional analysis of a gene list (Gene Ontology)

Gene expression profiles in tumors from breast cancer patients were compared to expression profiles in healthy tissue. This comparison revealed 991 overexpressed genes and 1422 downregulated genes in tumors. The gene lists are available on moodle.

Analyze the list of the 991 overexpressed genes using the GO Enrichment analysis tool on the [Panther website](http://geneontology.org/) and choosing the Cellular component ontology.

::: {#exr-1 .custom}
Explain the meaning of the different columns presented.
:::

::: {#exr-1 .custom}
Which GO term is most enriched in the gene list? Consult the meaning of this term. Is this a consistent result given that these are genes overexpressed in tumors?
:::

::: {#exr-1 .custom}
Which GO term is the most underrepresented in this list?
:::

Repeat the analysis using GO biological process (complete). Rank the results according to the False Discovery Rate (FDR). 

::: {#exr-1 .custom}
Which enrichment is most significant? Are the results consistent in your opinion?
:::

Now analyze the list of genes that are under-expressed in tumors (GO biological process).

::: {#exr-1 .custom}
To which major types of processes do the down-regulated genes belong?
:::

## Dotplot and optimal alignments (with EMBOSS tools)

We will use EMBOSS, a suite of tools for sequence analysis. You can access it [here](https://www.ebi.ac.uk/jdispatcher/emboss).

### Comparison of 2 myotubularin sequences

Search for **MTMR3_HUMAN** (Q13615) and **Q9W1Q6_DROME** (Q9W1Q6) sequences in UniProt and compare them with:

1. the dotplot method (dotmatcher program). Don’t forget to adjust parameters to decrease noise
2. the water program (local alignment) 
3. the needle program (global alignment)

::: {#exr-1 .custom}
Which similarity regions between the two sequences can be detected using dotplot? Is it in agreement with the domain organisation of the two proteins (see InterPro annotations of the 2 sequences)?
:::

Compare the results obtained using local and global alignments. 

::: {#exr-1 .custom}
Why is the score obtained using needle lower?
:::

::: {#exr-1 .custom}
How can you improve the global alignment? Test your hypothesis.
:::

::: {#exr-1 .custom}
What can you say about the C-terminal domain? How could you characterize this domain?
:::

### Self-comparison of a protein sequence

Search for the entries corresponding to the *aef1 gene* of *Drosophila melanogaster* in [UniProt](https://www.uniprot.org/). Open the **SwissProt** protein. 

::: {#exr-1 .custom}
Which domain(s) are present? To identify the domain(s) present, use the InterPro links from UniProt by navigating to `External links -> View protein in InterPro`.
:::

::: {#exr-1 .custom}
Represent schematically the result of a self-comparison of this sequence using the dotplot method.
:::

#### Connection to the Server

For many bioinformatics tools, there is a command-line alternative. These alternatives are often faster, more powerful, and more flexible.

To learn how to connect to the server for practical work, refer to the [Server Connection Guide](../help/server_connection_guide.qmd).

Once you're connected, start by creating a working directory for this session and navigating into it.

**mkdir**

The `mkdir` command stands for "make directory" and is used to create a new folder in the file system. You can create your directory like this:

```bash
mkdir <directory_name>
```

**cd**

The cd command stands for "change directory", allows you to move into a different folder within the file system. Use it as follows:

```bash
cd <directory>
```

::: {.callout-tip collapse="true"}
## Solution
```bash
mkdir tp2
cd tp2
```
:::

::: {.callout-note}
## Help
If you need help with a command, display its help using:
 - `<command-h` or `<command--help` for short help messages.
 - `man <command>` to display the full manual of a command.
:::


#### Download of protein sequence

You can download the sequence on the server. On the UniProt page of the protein, click on `Download`, and choose `Format (canonical)`. To download directly on the server, use Generate URL for API and copy the URL.

**wget**

The `wget` command is a tool used to download files from the web via HTTP, HTTPS, or FTP protocols directly from the command line.

An *API* (Application Programming Interface) is a system that allows you to send requests to a server. In biology, servers like NCBI or UniProt can be accessed through APIs to retrieve data and perform analyses.

To use `wget`, simply run the command followed by the URL of the file you want to download. For example:

```bash
wget http://example.com/file.txt
```

This will download the file file.txt from the specified URL to your current directory.

::: {.callout-tip collapse="true"}
## Solution
```bash
wget https://rest.uniprot.org/uniprotkb/P39413.fasta
```
:::

#### Dotmatcher

Run EMBOSS in the command line to perform a self-comparison of this sequence using the dotmatcher with windowsize of 10, and a threshold of 30.

```bash
dotmatcher -asequence <fastaA> -bsequence <fastaB> -windowsize <size> -threshold <threshold> -graph <graph_type>

```

Options: 

- `asequence`: The first sequence file to compare (in FASTA format). Example: `-asequence sequenceA.fasta`
- `bsequence`: The second sequence file to compare (in FASTA format). Example: `-asequence sequenceB.fasta`
- `windowsize`: The number of characters considered for matching at each position.
- `threshold`: The minimum similarity score for a match to be considered significant.
- `graph`: The format for the output graph (e.g., `png`, `pdf`, `svg`).

::: {.callout-tip collapse="true"}
## Solution
```bash
dotmatcher -asequence P39413.fasta -bsequence P39413.fasta -windowsize 10 -threshold 30 -graph png
```
:::

You can check the output has been generated by using the `ls` command.

**ls**

The `ls` command is used to list the contents of a directory in Linux. It provides a way to see files and subdirectories within the specified directory.

```bash
ls <directory>
```

If you want display the content of the current directory, use only:
```bash
ls 
```

The following files are in the current directory:

- `P39413.fasta`
- `dotmatcher.1.png`

To view the PNG file, it's best to open it locally. Transfer it from the server to your computer first.

**scp**

The `scp` command stands for "secure copy protocol." It is used to securely transfer files between a local computer and a remote server or between two remote servers over an encrypted SSH connection. This ensures that the data is protected during transfer.

To copy file from a server to your computer, **open a new terminal** and use `scp` like this:

```bash
scp <username>@<server_adress>:<source_file_path> <target_file_path>
```

::: {.callout-note}
## View the path of a file
If you not sure of the path .png file, use the command `realpath` to known it.
`realpath <file>` 
:::

::: {.callout-tip collapse="true"}
## Solution
```bash
scp <username>@tp.lbgi.fr:~/tp3/dotmatcher.1.png .
```

*Note: Replace `<login>` with your username. The tilde `~` is a shortcut for your home directory `/home/<username>`.*
:::

Now that the HTML file is on your computer, you can access it like any other file using your file explorer.

::: {#exr-1 .custom}
Is the result in agreement with your expectations? Which additional information appears?
:::

