# Practical - Analysis of eukaryotic sequences

## Ensembl genome browser

An exome from a patient with a retinal disease has been analyzed. The sequence of a mutated exon (109 bp) is available on Moodle.

Go to the [Ensembl genome browser](https://www.ensembl.org/index.html).


###  Mapping an exon sequence to the human genome

Open the BLAST/BLAT page. 

::: {#exr-1 .custom}
Is BLAT relevant to map our transcript on the genome? Why doesn't use BLAST?
:::

Perform the search.

::: {#exr-1 .custom}
What is the localization of the exonic region (chromosome, strand)? What is the corresponding gene?
:::

Display alignment.

::: {#exr-1 .custom}
Which variation(s) are observed on the patient exon compared to the reference genome?
:::

### GPR179 Gene

Select the gene.

**Isoforms (splice variants)**

::: {#exr-1 .custom}
How many protein coding transcripts are associated to this gene?
:::

::: {#exr-1 .custom}
According to the flags of the transcript table, which transcript is the more reliable?
:::

::: {#exr-1 .custom}
How many exons are present in this transcript?
:::

**Protein: function, GO annotation, and expression**

In a new window, search for the protein encoded by this gene in [SwissProt](https://www.uniprot.org/).

::: {#exr-1 .custom}
What is the protein function according to SwissProt?
:::

::: {#exr-1 .custom}
GO annotations: look at the list of synonyms associated with the GO molecular function of the protein. Does standardization make sense in this case?
:::

::: {#exr-1 .custom}
In which tissue is the gene expressed?
:::

**Phenotype (Ensembl, Gene tab)**

::: {#exr-1 .custom}
Which phenotype(s) is linked to this gene? Is it consistent with the exome analysis?
:::

### Annotated genomic region

Display the GPR179 genomic region (region in details). Zoom out to have a good overview.

::: {#exr-1 .custom}
To which exon does the patient sequence correspond ?
:::

**Gene prediction (ab initio + similarity)**

Configure this page (left panel) to display:

- Genes and transcripts / Prediction transcripts: Genscan predictions
- mRNA and protein alignments
  - mRNA alignments: display human cDNAs
  - protein alignments: display Proteins (mammals) from Uniprot

::: {#exr-1 .custom}
Compare information provided by Genscan (ab initio prediction), cDNA and protein alignments.
:::

**Repetitive elements**

Configure the page to display repeats (Repeat regions/All repeats) and conserved elements using Comparative genomics:

- Conservation regions/Constrained elements for eutherian mammals
- BLASTz/LASTz alignments with Chimpanzee, Mouse, crocodile, Zebrafish.
  
::: {#exr-1 .custom}
What is conserved in these different species?
:::

Retrieve the genomic region with 10000 bp 5’ and 3’ flanking sequence using Export data (fasta sequence, unmasked, text) or use the genomic region available on Moodle.

Analyze this sequence with [RepeatMasker](www.repeatmasker.org/) using default parameters (don’t hesitate to refresh the result page).

::: {#exr-1 .custom}
Which type of repeated element is the most represented in the genomic region?
:::

::: {#exr-1 .custom}
Display the annotation output and have a look at the 1st Alu repeat in the list. Can you identify a typical feature in this Alu repeat?
:::

::: {#exr-1 .custom}
To get a concrete idea of the importance of repetitive elements in the human genome, display the masked region.
:::

**Regulation (Optional)**

::: {#exr-1 .custom}
According to regulatory features, can we have information about GPR179 promoter? How do you explain it?
:::

::: {#exr-1 .custom}
Is it the same for the neighbor gene SOC7?
:::

Display the same region in the UCSC genome browser (by following the hypertext link) and display CpG islands.

## Functional analysis of a gene list

Another patient with a retinal disease exhibits several mutations including a mutation in a gene of completely unknown function. We only know that this gene is co-expressed with other genes (list available on Moodle).

**GO enrichment analysis**

Use the website of the [Gene Ontology](http://www.geneontology.org/).

Perform a functional enrichment analysis (Biological process ontology) of this list of genes in comparison to human genes.

::: {#exr-1 .custom}
What is the meaning of the different columns in the result table?
:::

::: {#exr-1 .custom}
Sort the results according to the P Value. Is the mutation a good candidate to explain the retinal disease of the patient?
:::

**Network analysis with STRING**

Use the website of [String](https://string-db.org/).

Visualize the functional links between the genes in the list with STRING (using the “Multiple proteins” form).

::: {#exr-1 .custom}
Which main types of links are observed between the genes of this list?
:::

::: {#exr-1 .custom}
Analyze the network (Analysis). Are there more links than expected in this list?
:::

::: {#exr-1 .custom}
Is the STRING analysis in agreement with the previous one?
:::